server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      hibernate:
          SQL: DEBUG
management:
  endpoints:
    web:
      exposure:
#        include: *
        include: info, health, metrics, prometheus


info:
  app: Spring Boot 2 Essentials by Carara
  github: https://github.com/cararax